name: PowerShell Script Execution

on:
  schedule:
    - cron: '* 0 * * *'  # <-- runs every midnight

jobs:
  run-powershell:
    runs-on: windows-latest  # <-- runs on Windows 11
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # <-- check out the code from the repository

      - name: Run PowerShell Script
        shell: powershell
        run: .\bot.ps1           # <-- exeecute the bot script
